use serde::{Deserialize, Serialize};
use std::path::PathBuf;
use std::fs;

use crate::error::{ConfigError, Result};

/// Main configuration structure for ArchForge
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct Config {
    pub model: ModelConfig,
    pub build: BuildConfig,
    pub ui: UIConfig,
    pub swarm: SwarmConfig,
    pub deploy: DeployConfig,
}

impl Config {
    /// Load configuration from default paths
    pub fn load() -> Result<Self> {
        let config_path = Self::config_path()?;

        if !config_path.exists() {
            // Create default config
            let default_config = Self::default();
            default_config.save()?;
            return Ok(default_config);
        }

        let content = fs::read_to_string(&config_path)
            .map_err(|e| ConfigError::Io(e))?;

        // Simple parsing for basic types
        Ok(Self::parse_toml(&content)
            .map_err(|e| ConfigError::InvalidFormat(e))?)
    }

    /// Simple TOML parser for basic configuration
    fn parse_toml(content: &str) -> std::result::Result<Self, String> {
        let mut config = Self::default();

        for line in content.lines() {
            let line = line.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }

            if let Some((key, value)) = line.split_once('=') {
                let key = key.trim();
                let value = value.trim().trim_matches('"');

                match key {
                    "makepkg_path" => config.build.makepkg_path = PathBuf::from(value),
                    "aur_helper" => config.build.aur_helper = value.to_string(),
                    "theme" => config.ui.theme = value.to_string(),
                    "vim_mode" => config.ui.vim_mode = value.parse().unwrap_or(true),
                    _ => {}
                }
            }
        }

        Ok(config)
    }

    /// Get config path: ~/.config/archforge/config.toml
    pub fn config_path() -> Result<PathBuf> {
        let mut path = dirs::config_dir()
            .ok_or_else(|| ConfigError::NotFound("Config directory".to_string()))?;
        path.push("archforge");
        path.push("config.toml");
        Ok(path)
    }

    /// Save configuration to file
    pub fn save(&self) -> Result<()> {
        let config_path = Self::config_path()?;

        // Ensure directory exists
        if let Some(parent) = config_path.parent() {
            fs::create_dir_all(parent)
                .map_err(|e| ConfigError::Io(e))?;
        }

        // Simple TOML-like format
        let content = format!(
            r#"# ArchForge Configuration
# Generated by ArchForge

[build]
makepkg_path = "{}"
aur_helper = "{}"

[ui]
theme = "{}"
vim_mode = {}
"#,
            self.build.makepkg_path.display(),
            self.build.aur_helper,
            self.ui.theme,
            self.ui.vim_mode
        );

        fs::write(&config_path, content)
            .map_err(|e| ConfigError::Io(e))?;

        Ok(())
    }
}

/// Local LLM model configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ModelConfig {
    /// Path to GGUF model file
    pub path: PathBuf,

    /// Model temperature (0.0-1.0)
    #[serde(default = "default_temperature")]
    pub temperature: f32,

    /// Max tokens to generate
    #[serde(default = "default_max_tokens")]
    pub max_tokens: usize,

    /// Enable GPU acceleration
    #[serde(default)]
    pub cuda: bool,

    /// Model cache directory
    #[serde(default = "default_cache_dir")]
    pub cache_dir: PathBuf,
}

impl Default for ModelConfig {
    fn default() -> Self {
        Self {
            path: default_model_path(),
            temperature: default_temperature(),
            max_tokens: default_max_tokens(),
            cuda: false,
            cache_dir: default_cache_dir(),
        }
    }
}

fn default_temperature() -> f32 {
    0.1
}

fn default_max_tokens() -> usize {
    4096
}

fn default_cache_dir() -> PathBuf {
    let mut dir = dirs::cache_dir().unwrap_or_else(|| PathBuf::from("/tmp"));
    dir.push("archforge");
    dir.push("models");
    dir
}

fn default_model_path() -> PathBuf {
    let mut path = default_cache_dir();
    path.push("pkgbuild-v1.gguf");
    path
}

/// Build engine configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BuildConfig {
    /// Path to makepkg binary
    #[serde(default = "default_makepkg_path")]
    pub makepkg_path: PathBuf,

    /// AUR helper (yay, paru, or custom)
    #[serde(default = "default_aur_helper")]
    pub aur_helper: String,

    /// Build directory
    #[serde(default = "default_build_dir")]
    pub build_dir: PathBuf,

    /// Number of parallel make jobs
    #[serde(default = "default_make_jobs")]
    pub make_jobs: u32,

    /// Enable ASLR for builds
    #[serde(default = "default_aslr")]
    pub aslr: bool,
}

impl Default for BuildConfig {
    fn default() -> Self {
        Self {
            makepkg_path: default_makepkg_path(),
            aur_helper: default_aur_helper(),
            build_dir: default_build_dir(),
            make_jobs: default_make_jobs(),
            aslr: default_aslr(),
        }
    }
}

fn default_makepkg_path() -> PathBuf {
    PathBuf::from("/usr/bin/makepkg")
}

fn default_aur_helper() -> String {
    "paru".to_string()
}

fn default_build_dir() -> PathBuf {
    let mut dir = dirs::cache_dir().unwrap_or_else(|| PathBuf::from("/tmp"));
    dir.push("archforge");
    dir.push("builds");
    dir
}

fn default_make_jobs() -> u32 {
    4 // Default to 4 jobs if CPU count unavailable
}

fn default_aslr() -> bool {
    true
}

/// UI configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UIConfig {
    /// Color theme
    #[serde(default = "default_theme")]
    pub theme: String,

    /// Enable vim keybindings
    #[serde(default = "default_vim_mode")]
    pub vim_mode: bool,

    /// Tab size for PKGBUILD preview
    #[serde(default = "default_tab_size")]
    pub tab_size: u16,

    /// Show line numbers in preview
    #[serde(default = "default_line_numbers")]
    pub line_numbers: bool,
}

impl Default for UIConfig {
    fn default() -> Self {
        Self {
            theme: default_theme(),
            vim_mode: default_vim_mode(),
            tab_size: default_tab_size(),
            line_numbers: default_line_numbers(),
        }
    }
}

fn default_theme() -> String {
    "arch_dark".to_string()
}

fn default_vim_mode() -> bool {
    true
}

fn default_tab_size() -> u16 {
    4
}

fn default_line_numbers() -> bool {
    true
}

/// P2P swarm configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SwarmConfig {
    /// Enable P2P networking
    #[serde(default)]
    pub enabled: bool,

    /// Listen on these addresses
    #[serde(default = "default_listen_addrs")]
    pub listen_addrs: Vec<String>,

    /// Enable mDNS peer discovery
    #[serde(default = "default_mdns")]
    pub mdns: bool,

    /// Enable telemetry sharing
    #[serde(default = "default_telemetry")]
    pub telemetry: bool,

    /// Database path
    #[serde(default = "default_db_path")]
    pub db_path: PathBuf,
}

impl Default for SwarmConfig {
    fn default() -> Self {
        Self {
            enabled: false,
            listen_addrs: default_listen_addrs(),
            mdns: default_mdns(),
            telemetry: default_telemetry(),
            db_path: default_db_path(),
        }
    }
}

fn default_listen_addrs() -> Vec<String> {
    vec!["/ip4/0.0.0.0/tcp/0".to_string()]
}

fn default_mdns() -> bool {
    true
}

fn default_telemetry() -> bool {
    false
}

fn default_db_path() -> PathBuf {
    let mut dir = dirs::data_dir().unwrap_or_else(|| PathBuf::from("/var/lib"));
    dir.push("archforge");
    dir.push("swarm.db");
    dir
}

/// Deployment configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeployConfig {
    /// AUR username (for uploads)
    pub aur_user: Option<String>,

    /// AUR API key
    pub aur_key: Option<String>,

    /// Docker repository
    pub docker_repo: Option<String>,

    /// Default deployment target
    #[serde(default = "default_deploy_target")]
    pub default_target: String,

    /// Bubblewrap path
    #[serde(default = "default_bwrap_path")]
    pub bwrap_path: PathBuf,
}

impl Default for DeployConfig {
    fn default() -> Self {
        Self {
            aur_user: None,
            aur_key: None,
            docker_repo: None,
            default_target: default_deploy_target(),
            bwrap_path: default_bwrap_path(),
        }
    }
}

fn default_deploy_target() -> String {
    "aur".to_string()
}

fn default_bwrap_path() -> PathBuf {
    PathBuf::from("/usr/bin/bwrap")
}