use archforge::{ai::ChutesClient, Cli, Config, VERSION};
use clap::Parser;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    eprintln!("ArchForge v{} starting...", VERSION);

    // Parse CLI arguments
    let cli = Cli::parse();

    // Run the command
    match cli.command {
        archforge::cli::Commands::Generate { description, output, quiet: _, ai_provider, api_key } => {
            generate(&description, output, ai_provider, api_key)?;
        }
        archforge::cli::Commands::Build { package, install: _, nodeps: _ } => {
            build(&package)?;
        }
        archforge::cli::Commands::Search { query, json, limit: _ } => {
            search(&query, json)?;
        }
        archforge::cli::Commands::Info { package } => {
            info(&package)?;
        }
        archforge::cli::Commands::Deploy { package, target: _, yes: _ } => {
            deploy(&package)?;
        }
        archforge::cli::Commands::Interactive { no_model: _ } => {
            run_tui()?;
        }
        archforge::cli::Commands::Init { name, template: _, directory } => {
            init(&name, directory)?;
        }
        archforge::cli::Commands::Swarm(cmd) => {
            swarm(cmd)?;
        }
        archforge::cli::Commands::Status => {
            status()?;
        }
        archforge::cli::Commands::Cache(cmd) => {
            cache(cmd)?;
        }
    }

    Ok(())
}

fn generate(
    description: &str,
    output: Option<std::path::PathBuf>,
    ai_provider: archforge::ai::AiProvider,
    api_key: Option<String>,
) -> Result<(), Box<dyn std::error::Error>> {
    eprintln!("Generating PKGBUILD for: {}", description);

    match ai_provider {
        archforge::ai::AiProvider::Chutes => {
            let api_key = api_key.or_else(|| {
                std::env::var("CHUTES_API_KEY").ok()
            }).expect("API key required. Set CHUTES_API_KEY env var or use --api-key");

            let client = ChutesClient::new(api_key);
            match client.generate_pkgbuild(description) {
                Ok(pkgbuild) => {
                    if let Some(path) = output {
                        std::fs::write(&path, &pkgbuild)?;
                        eprintln!("PKGBUILD saved to: {}", path.display());
                    } else {
                        println!("{}", pkgbuild);
                    }
                }
                Err(e) => {
                    eprintln!("AI generation failed: {}. Falling back to template...", e);
                    generate_fallback(description, output)?;
                }
            }
        }
        archforge::ai::AiProvider::Local => {
            eprintln!("Local AI provider not implemented yet. Using fallback.");
            generate_fallback(description, output)?;
        }
        archforge::ai::AiProvider::Openai => {
            eprintln!("OpenAI provider not implemented yet. Using fallback.");
            generate_fallback(description, output)?;
        }
    }

    Ok(())
}

fn generate_fallback(
    description: &str,
    output: Option<std::path::PathBuf>,
) -> Result<(), Box<dyn std::error::Error>> {
    // Generate PKGBUILD content (static template fallback)
    let output_text = format!(
        r#"# Generated by ArchForge
# Description: {}

pkgname=archforge-{}
pkgver=0.1.0
pkgrel=1
pkgdesc="Package generated from: {}"
arch=('x86_64')
url="https://example.com"
license=('MIT')
depends=('glibc' 'gcc-libs')
makedepends=('cargo' 'rust')
optdepends=('extra-dep: for extra features')
provides=('archforge-generated')
conflicts=('archforge-generated')
source=("https://example.com/archive/v$pkgver.tar.gz")
sha256sums=('SKIP')

build() {{
    cd "$pkgname-$pkgver"
    cargo build --release
}}

package() {{
    cd "target/release"
    install -Dm755 {} "$pkgdir/usr/bin/{}"
}}
"#,
        description,
        slugify(description),
        description,
        slugify(description),
        slugify(description)
    );

    if let Some(path) = output {
        std::fs::write(&path, &output_text)?;
        eprintln!("PKGBUILD saved to: {}", path.display());
    } else {
        println!("{}", output_text);
    }

    Ok(())
}

fn build(package: &str) -> Result<(), Box<dyn std::error::Error>> {
    eprintln!("Building package: {}", package);

    // Try to parse PKGBUILD if it exists
    let pkgbuild_path = std::path::PathBuf::from(package);
    let actual_path = if pkgbuild_path.is_dir() {
        pkgbuild_path.join("PKGBUILD")
    } else {
        pkgbuild_path
    };

    if actual_path.exists() {
        eprintln!("Found PKGBUILD at: {}", actual_path.display());

        // Check if makepkg is available
        if std::process::Command::new("makepkg").arg("--version").output().is_ok() {
            eprintln!("Running makepkg...");
            let output = std::process::Command::new("makepkg")
                .args(&["--nobuild", "--nodeps"])
                .current_dir(actual_path.parent().unwrap_or(&std::path::PathBuf::from(".")))
                .output()?;

            if output.status.success() {
                eprintln!("PKGBUILD validation successful!");
            } else {
                eprintln!("PKGBUILD has errors:");
                eprintln!("{}", String::from_utf8_lossy(&output.stderr));
            }
        } else {
            eprintln!("makepkg not found. Install base-devel package.");
        }
    } else {
        eprintln!("PKGBUILD not found at: {}", actual_path.display());
    }

    Ok(())
}

fn search(query: &str, json: bool) -> Result<(), Box<dyn std::error::Error>> {
    eprintln!("Searching AUR for: {}", query);

    // Query AUR RPC
    let url = format!(
        "https://aur.archlinux.org/rpc.php?v=5&type=search&arg={}",
        urlencoding::encode(query)
    );

    let response = reqwest::blocking::get(&url)?
        .json::<serde_json::Value>()?;

    if json {
        println!("{}", serde_json::to_string_pretty(&response)?);
    } else {
        println!("Search results for '{}':", query);
        println!("{}", "=".repeat(60));

        if let Some(results) = response.get("results").and_then(|r| r.as_array()) {
            for (i, result) in results.iter().enumerate().take(10) {
                let name = result.get("Name").and_then(|v| v.as_str()).unwrap_or("?");
                let version = result.get("Version").and_then(|v| v.as_str()).unwrap_or("?");
                let desc = result.get("Description").and_then(|v| v.as_str()).unwrap_or("");
                let votes = result.get("Votes").and_then(|v| v.as_u64()).unwrap_or(0);

                println!("{}. {} {} ({} votes)", i + 1, name, version, votes);
                println!("   {}", desc.chars().take(60).collect::<String>());
                println!();
            }
        }
    }

    Ok(())
}

fn info(package: &str) -> Result<(), Box<dyn std::error::Error>> {
    eprintln!("Getting info for: {}", package);

    let url = format!(
        "https://aur.archlinux.org/rpc.php?v=5&type=info&arg={}",
        urlencoding::encode(package)
    );

    let response = reqwest::blocking::get(&url)?
        .json::<serde_json::Value>()?;

    if let Some(result) = response.get("results").and_then(|r| r.as_object()) {
        println!("Package: {}", result.get("Name").and_then(|v| v.as_str()).unwrap_or("?"));
        println!("Version: {}", result.get("Version").and_then(|v| v.as_str()).unwrap_or("?"));
        println!("Description: {}", result.get("Description").and_then(|v| v.as_str()).unwrap_or(""));
        println!("Maintainer: {}", result.get("Maintainer").and_then(|v| v.as_str()).unwrap_or("unknown"));
        println!("Votes: {}", result.get("Votes").and_then(|v| v.as_u64()).unwrap_or(0));
        println!("Popularity: {:.2}", result.get("Popularity").and_then(|v| v.as_f64()).unwrap_or(0.0));
        println!("\nDependencies:");
        if let Some(deps) = result.get("Depends").and_then(|v| v.as_array()) {
            for dep in deps {
                println!("  - {}", dep.as_str().unwrap_or("?"));
            }
        }
        if let Some(makedeps) = result.get("MakeDepends").and_then(|v| v.as_array()) {
            if !makedeps.is_empty() {
                println!("\nBuild Dependencies:");
                for dep in makedeps {
                    println!("  - {}", dep.as_str().unwrap_or("?"));
                }
            }
        }
        println!("\nURL: {}", result.get("URL").and_then(|v| v.as_str()).unwrap_or("none"));
    } else {
        eprintln!("Package not found in AUR");
    }

    Ok(())
}

fn deploy(package: &str) -> Result<(), Box<dyn std::error::Error>> {
    eprintln!("Deploying package: {}", package);
    eprintln!("\nDeployment options:");
    eprintln!("  1. AUR (requires git + SSH key)");
    eprintln!("  2. Docker (requires Docker installed)");
    eprintln!("  3. Flatpak (requires flatpak-builder)");
    eprintln!("  4. Nix flake (requires Nix)");
    eprintln!("\nTo deploy, use:");
    eprintln!("  archforge deploy ./mypkg --target aur");
    eprintln!("  archforge deploy ./mypkg --target docker");
    Ok(())
}

fn run_tui() -> Result<(), Box<dyn std::error::Error>> {
    // Check if we're in a TTY
    if !atty::is(atty::Stream::Stdout) {
        eprintln!("Error: TUI mode requires a terminal");
        eprintln!("Use 'archforge generate \"description\"' for non-interactive mode");
        std::process::exit(1);
    }

    archforge::tui::run_tui()?;
    Ok(())
}

fn init(
    name: &str,
    directory: Option<std::path::PathBuf>,
) -> Result<(), Box<dyn std::error::Error>> {
    eprintln!("Initializing project: {}", name);

    let dir = directory.unwrap_or_else(|| std::path::PathBuf::from(name));

    if dir.exists() {
        eprintln!("Error: Directory already exists: {}", dir.display());
        std::process::exit(1);
    }

    std::fs::create_dir_all(&dir)?;

    let pkgbuild = format!(
        r#"# ArchForge PKGBUILD
pkgname={}
pkgver=0.1.0
pkgrel=1
pkgdesc="A package generated by ArchForge"
arch=('x86_64')
url="https://github.com/{}"
license=('MIT')
depends=('glibc')
makedepends=('cargo')
source=("$url/archive/v$pkgver.tar.gz")
sha256sums=('SKIP')

build() {{
    cd "$pkgname-$pkgver"
    cargo build --release
}}

package() {{
    cd "target/release"
    install -Dm755 {} "$pkgdir/usr/bin/{}"
}}
"#,
        name,
        name,
        name,
        name
    );

    std::fs::write(dir.join("PKGBUILD"), pkgbuild)?;
    std::fs::write(dir.join(".gitignore"), "target/\n*.pkg.tar.zst\n")?;

    println!("Created project at: {}", dir.display());
    println!("Next steps:");
    println!("  cd {}", dir.display());
    println!("  # Edit PKGBUILD as needed");
    println!("  archforge build .");
    Ok(())
}

fn swarm(cmd: archforge::cli::SwarmCommands) -> Result<(), Box<dyn std::error::Error>> {
    match cmd {
        archforge::cli::SwarmCommands::Start { telemetry: _ } => {
            eprintln!("[SWARM] P2P networking - Coming soon!");
            eprintln!("[SWARM] This will enable telemetry sharing with other ArchForge users.");
        }
        archforge::cli::SwarmCommands::Stop => {
            eprintln!("[SWARM] Stopping swarm network...");
        }
        archforge::cli::SwarmCommands::Peers => {
            eprintln!("[SWARM] Connected peers: 0 (P2P coming soon)");
        }
        archforge::cli::SwarmCommands::Sync { address: _ } => {
            eprintln!("[SWARM] Sync - Coming soon!");
        }
    }
    Ok(())
}

fn status() -> Result<(), Box<dyn std::error::Error>> {
    println!("ArchForge Status");
    println!("================");
    println!("Version: {}", VERSION);

    // Check for makepkg
    if std::process::Command::new("makepkg").arg("--version").output().is_ok() {
        println!("Makepkg: Installed");
    } else {
        println!("Makepkg: NOT INSTALLED (install base-devel)");
    }

    // Check for AUR helpers
    if std::process::Command::new("paru").arg("--version").output().is_ok() {
        println!("Paru: Installed");
    } else if std::process::Command::new("yay").arg("--version").output().is_ok() {
        println!("Yay: Installed");
    } else {
        println!("AUR helper: Not found (install paru or yay)");
    }

    // Config location
    println!("\nConfig: ~/.config/archforge/config.toml");

    Ok(())
}

fn cache(cmd: archforge::cli::CacheCommands) -> Result<(), Box<dyn std::error::Error>> {
    match cmd {
        archforge::cli::CacheCommands::Stats => {
            println!("Cache Statistics");
            println!("================");

            if let Some(cache_dir) = dirs::cache_dir() {
                let archforge_cache = cache_dir.join("archforge");
                if archforge_cache.exists() {
                    // Count files
                    let files: Vec<_> = walkdir::WalkDir::new(&archforge_cache)
                        .into_iter()
                        .filter_map(|e| e.ok())
                        .filter(|e| e.file_type().is_file())
                        .collect();

                    let size: u64 = files.iter()
                        .map(|e| e.metadata().map(|m| m.len()).unwrap_or(0))
                        .sum();

                    println!("Files: {}", files.len());
                    println!("Size: {} bytes ({:.2} MB)", size, size as f64 / 1024.0 / 1024.0);
                } else {
                    println!("Cache directory: Empty");
                }
            }
        }
        archforge::cli::CacheCommands::Models => {
            println!("Clearing model cache... (Not implemented yet)");
        }
        archforge::cli::CacheCommands::Builds => {
            if let Some(cache_dir) = dirs::cache_dir() {
                let build_cache = cache_dir.join("archforge/builds");
                if build_cache.exists() {
                    std::fs::remove_dir_all(&build_cache)?;
                    println!("Build cache cleared");
                } else {
                    println!("Build cache: Already empty");
                }
            }
        }
        archforge::cli::CacheCommands::All => {
            println!("Clearing all caches...");
            if let Some(cache_dir) = dirs::cache_dir() {
                let archforge_cache = cache_dir.join("archforge");
                if archforge_cache.exists() {
                    std::fs::remove_dir_all(&archforge_cache)?;
                    println!("All caches cleared");
                }
            }
        }
    }
    Ok(())
}

/// Convert description to slug for package name
fn slugify(s: &str) -> String {
    let cleaned: String = s
        .to_lowercase()
        .chars()
        .filter(|c| c.is_alphanumeric() || *c == '-' || *c == '_' || *c == ' ')
        .collect();
    cleaned
        .split_whitespace()
        .collect::<Vec<_>>()
        .join("-")
        .trim_matches('-')
        .to_string()
}